site_name: Precision Medicine 1
nav:
  - Introduction: intro.md
  - Lab1 - Sequencing data formats and visualization: lab1.md
  - Lab2 - Sequencing Quality Control: lab2.md
  - Lab3 - Germline variants: lab3.md
  - Lab4 - Somatic variants: lab4.md

theme: readthedocs
extra_css: [extra.css]
markdown_extensions:
  - abbr
  - attr_list
  - pymdownx.details
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
      base_path: ["docs/"]
      url_download: "True"
  - mdx_spanner
  - admonition
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

