site_name: Laboratory techniques and data analysis in precision medicine 1
nav:
  - Introduction: intro.md
  - Lab1 - Sequencing data format and visualization: lab1.md
  - Lab2 - Sequencing quality control: lab2.md
  - Lab3 - Germline variants: lab3.md
  - Lab4 - Somatic variants: lab4.md

theme: material
extra_css: [extra.css]
markdown_extensions:
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - abbr
  - attr_list
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
      base_path: ["docs/"]
      url_download: "True"
  - mdx_spanner
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
